name: .NET - Build, test and publish reusable workflow

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest

      dotnet-version:
        required: false
        type: string
        default: 9.0.x
        
      publish:
        required: false
        type: boolean
        default: true
        
      generate-build-number:
        required: false
        type: boolean
        default: false
        
      additional-dotnet-version:
        required: false
        type: string
        default: ''
        
      dotnet-quality:
        required: false
        type: string
        default: 'ga'
        
      workloads:
        required: false
        type: string
        default: ''
        
      windows-sdk-version:
        required: false
        type: string
        default: ''
        
      windows-sdk-version2:
        required: false
        type: string
        default: ''
        
      windows-sdk-version3:
        required: false
        type: string
        default: ''
        
      windows-sdk-version4:
        required: false
        type: string
        default: ''
        
      dynamic-env:
        required: false
        type: string
        default: ''
        
      fetch-depth:
        required: false
        type: number
        default: 0
        
      conventional-commits-publish-conditions:
        required: false
        type: boolean
        default: false
        
      project-path:
        required: false
        type: string
        default: ''
        
      additional-project-path:
        required: false
        type: string
        default: ''
        
      additional-command:
        required: false
        type: string
        default: ''
        
      configuration:
        required: false
        type: string
        default: Release
        
      use-msbuild:
        required: false
        type: boolean
        default: false
        
      install-latest-msbuild:
        required: false
        type: boolean
        default: false
        
      install-tizen:
        required: false
        type: boolean
        default: false
        
      custom-workload-macos:
        required: false
        type: string
        default: ''
        
      custom-workload-windows:
        required: false
        type: string
        default: ''
        
      vs-prerelease:
        required: false
        type: boolean
        default: true
        
      enable-caching:
        required: false
        type: boolean
        default: false
        
      run-tests:
        required: false
        type: boolean
        default: true
        
      additional-test-arguments:
        required: false
        type: string
        default: ''
        
      create-release:
        required: false
        type: boolean
        default: true
        
      asset-path1:
        required: false
        type: string
        default: ''
        
      asset-name1:
        required: false
        type: string
        default: ''
        
      asset-content-type1:
        required: false
        type: string
        default: application/x-msi
        
      asset-path2:
        required: false
        type: string
        default: ''
        
      asset-name2:
        required: false
        type: string
        default: ''
        
      asset-content-type2:
        required: false
        type: string
        default: application/x-msi
        
      asset-path3:
        required: false
        type: string
        default: ''
        
      asset-name3:
        required: false
        type: string
        default: ''
        
      asset-content-type3:
        required: false
        type: string
        default: application/x-msi
        
      github-packages-path:
        required: false
        type: string
        default: ''
        
      deploy-web-assembly-path:
        required: false
        type: string
        default: ''
        
      deploy-web-assembly-repo:
        required: false
        type: string
        default: ''
        
    secrets:
      nuget-key:
        required: false
        
      virustotal-key:
        required: false

      personal-token:
        required: false

      api-key:
        required: false
        
      dynamic-secrets:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.os }}
    name: Build, test and publish
    env:
      # Disable the .NET logo in the console output.
      DOTNET_NOLOGO: true
      # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      # Disable sending .NET CLI telemetry to Microsoft.
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
      CONVENTIONAL-COMMITS-PUBLISH-CONDITIONS: 
        ${{ !inputs.conventional-commits-publish-conditions || 
        contains(join(github.event.commits.*.message), 'fix:') || 
        contains(join(github.event.commits.*.message), 'feat:') || 
        contains(join(github.event.commits.*.message), 'perf:') || 
        contains(join(github.event.commits.*.message), 'fix(') || 
        contains(join(github.event.commits.*.message), 'feat(') || 
        contains(join(github.event.commits.*.message), 'perf(') }}
      PUBLISH-TO-NUGET: ${{ !!secrets.nuget-key }}
      DYNAMIC_SECRETS: ${{ !!secrets.dynamic-secrets }}
      DYNAMIC_ENV: ${{ !!inputs.dynamic-env }}
      SCAN-BY-VIRUSTOTAL: ${{ !!secrets.virustotal-key }}
      IS-PERSONAL-TOKEN-AVAILABLE: ${{ !!secrets.personal-token }}
      TF_BUILD: ${{ inputs.install-tizen }}
      API_KEY: ${{ secrets.api-key }}
    
    steps:
    - name: Print build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: NTX
      run: echo ${{secrets.nuget-key}}
      

